### ISSUE TITLE
[PE-D] Minor functionally tweak

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-2/tp#169]
Maybe after there are no more cards you can just end the slideshow instead of throwing an error and make the user type in 'stop'

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: knotstoks/ped#6

**Comment by chownces** [comment]
Closing this as it is a new feature, which the team is not allowed to implement in v1.4
