### ISSUE TITLE
[PE-D] UG Import additional notes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-2/tp#179]
would be good to mention that it does not override the existing list, rather simply adds on :)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: lingshanng/ped#5

**Comment by jhlee1997** [comment]
- Now the UG states that "Imports flashcards from a CSV file and adds them to the existing list in LingoGO! (instead of replacing the current list)" so that users know that importing does not replace the current set of Flashcards but add on to it.
