### ISSUE TITLE
[PE-D] Incorrect directory displayed when exporting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-2/tp#186]
![image.png](https://raw.githubusercontent.com/yeppog/ped/master/files/f476458d-84c5-4f26-a402-6ee7b26ef0df.png)

When exporting the csv, the console shows that it is saved in `test.csv`, however, does not specify the proper directory. Since keying in `test.csv` when importing means that the file is taken from the current directory, the console output should also indicate that it is saved in the `data` folder.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yeppog/ped#6

**Comment by jhlee1997** [comment]
- Now that both import and export use the same folder "data", users will not be confused about the where the file will be stored. Furthermore, the UG also states that export will create a CSV file in the data folder. Thus, there is no need to specify the proper directory.
