### ISSUE TITLE
[PE-D] FileNotFoundException when exporting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-2/tp#188]
When exporting the data with erroneous file name as shown below, `FileNotFoundException` is not handled properly.

![image.png](https://raw.githubusercontent.com/yeppog/ped/master/files/6e4925d3-2dd4-4559-8580-3f04ad757741.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yeppog/ped#7

**Comment by jhlee1997** [comment]
- Now the export command has more extensive validity check for csv file name format. This check ensures that illegal file names involving quotation(") cannot be used.
